name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
      
            - name: List and Read File
              run: | 
                 echo "My first GitHub Actions Job"
                 run: ls -ltra
                 run: cat README.md

            - name: Generate ASCII Artifact
              run: cowsay -f dragon "Run for cover, I am a dragon....RAWR" >>dragon.txt
        
        

        

